WORLD_SPACE_REFERENCE_WIDTH = 1000
WORLD_SPACE_REFERENCE_HEIGHT = 1000

def set_world_size(width, height):
    global WORLD_SPACE_REFERENCE_WIDTH
    WORLD_SPACE_REFERENCE_WIDTH = width
    global WORLD_SPACE_REFERENCE_HEIGHT
    WORLD_SPACE_REFERENCE_HEIGHT = height